### PR TITLE
Add cross sbt build support

### PR DESCRIPTION
**Pull request by sslavic**
This patch adds support for building cross sbt variants of the sbt-scalabuff plugin, through use of [sbt-cross-building](https://github.com/jrudolph/sbt-cross-building) plugin.

With this patch applied one can e.g. from sbt console issue _**^ publish-local**_ command and have two sets of sbt-scalabuff plugin artifacts published in local ivy repository, one for scala 2.9.2 and sbt 0.12, and second one for scala 2.10 and sbt 0.13.

### CODE REVIEW

**Comment by SandroGrzicic** [comment]
Looks good. @aloiscochard please merge this and release a new version.

**Comment by sslavic** [comment]
In the release, please also consider including [upgrade to scalabuff 1.3.7](https://github.com/sbt/sbt-scalabuff/pull/15)

**Comment by tkawachi** [comment]
@aloiscochard Please merge it.

**Comment by dchenbecker** [comment]
Please, please, pretty please with cherries on top merge this.

**Comment by aloiscochard** [comment]
I must say that the cherries helped!

More seriously, as I'm not using this in production and not interested to work on it on my free time, I'm looking for someone able to take over this plugin.

Anyone interested?

**Comment by SandroGrzicic** [comment]
I think I can take over the project.

**Comment by dchenbecker** [comment]
@SandroGrzicic if you need help I'm happy to lend a hand. In any case, someone is going to need to publish this to typesafe's SBT repo.

**Comment by copumpkin** [comment]
+1 for the publish. This project is exactly what I need but I can't really depend on it until it's easily accessible for others.

**Comment by t3hnar** [comment]
Hi @SandroGrzicic, @aloiscochard, did you agree on taking over/transferring  this project?
Would be nice to finally get this build released against sbt 0.13

**Comment by aloiscochard** [comment]
Any member of the `sbt` organisation as plugin author can manage that project:
https://github.com/orgs/sbt/teams/plugin-authors

I think @SandroGrzicic that you can simply ask @jsuereth and will add you in that group.

**Comment by vallettea** [comment]
Hello, i'm struggling to make sbt-scalabuff work with sbt 0.13.
Can somebody tell me how to use this merge (or the latest version of the project) in my sbt `Build.scala` or `pluging.sbt` ?  thanks

**Comment by tkawachi** [comment]
sbt can fetch dependencies from github. I added following lines to `project/plugins.sbt` and it's working fine. (though it consumes compilation time of the plugin)

```
lazy val root = project.in(file(".")).dependsOn(scalabuff)

// replace uri and commit to what you want to use
// NOTE uri format is git://github.com/foo/bar.git#commit. Not git@github.com:foo/bar.git#commit
lazy val scalabuff = uri("git://github.com/tkawachi/sbt-scalabuff.git#47a1ab48a50ccd42c7c5a44d8ff605184e2b3707")
```

Another way is `publish` to your repo or `publishLocal` for local usage.

**Comment by vallettea** [comment]
thx @tkawachi

**Pull request merged**
